language: java

sudo: false

jdk:
  - oraclejdk8

services:
  - redis-server

script:
  - mvn clean package -Dgpg.skip=true -Dcheckstyle.skip=false -Drat.skip=false

after_success:
  - bash <(curl -s https://codecov.io/bash)